# Generated by Django 4.2.8 on 2023-12-18 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('days', models.IntegerField()),
                ('farms', models.IntegerField()),
                ('parcels', models.IntegerField()),
                ('discounts', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date_init', models.DateField()),
                ('date_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=True)),
                ('plan_subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.plansubscription')),
            ],
        ),
    ]
